@echo off
rem ========================================================================
rem                              Clean Project
rem ========================================================================
rem Script for Clean Project to clean Visual Studio temporary files, build
rem results, and files generated by popular Visual Studio add-ons.
rem
rem Clean Project:
rem     http://wf.codeplex.com/wikipage?title=Clean%20Project%20Overview
rem
rem GitHub's GitIgnore for Visual Studio
rem     https://github.com/github/gitignore/VisualStudio.gitignore
rem
rem ========================================================================

rem ============
rem Custom Help Message
rem ============
if "%1" == "help" goto HELP

rem ============
rem Ensure CleanProject is in path
rem ============
for %%f in (cleanproject.exe) do (
    if not exist "%%~dp$PATH:f" (
        echo ERROR:  %%f Executable is not in path
        goto EXIT
    )
)

set RF= 
set RD= 

rem ============
rem Build the Command Line
rem ============

rem User-specific files
set RF=%RF% /RF:.gitignore
set RD=%RD% /RD:.git

rem User-specific files
set RF=%RF% /RF:*.suo
set RF=%RF% /RF:*.user
set RF=%RF% /RF:*.sln.docstates

rem Build results
set RD=%RD% /RD:Debug
set RD=%RD% /RD:Release
set RD=%RD% /RD:x64
set RD=%RD% /RD:build
set RD=%RD% /RD:Bin
set RD=%RD% /RD:Obj

rem MSTest test Results
set RD=%RD% /RD:TestResult*
set RF=%RF% /RF:BuildLog.*

set RF=%RF% /RF:*_i.c
set RF=%RF% /RF:*_p.c
set RF=%RF% /RF:*.ilk
set RF=%RF% /RF:*.meta
set RF=%RF% /RF:*.obj
set RF=%RF% /RF:*.pch
set RF=%RF% /RF:*.pdb
set RF=%RF% /RF:*.pgc
set RF=%RF% /RF:*.pgd
set RF=%RF% /RF:*.rsp
set RF=%RF% /RF:*.sbr
set RF=%RF% /RF:*.tlb
set RF=%RF% /RF:*.tli
set RF=%RF% /RF:*.tlh
set RF=%RF% /RF:*.tmp
set RF=%RF% /RF:*.tmp_proj
set RF=%RF% /RF:*.log
set RF=%RF% /RF:*.vspscc
set RF=%RF% /RF:*.vssscc
set RF=%RF% /RF:.builds
set RF=%RF% /RF:*.pidb
set RF=%RF% /RF:*.log
set RF=%RF% /RF:*.scc

rem Visual C++ cache files
set RD=%RD% /RD:ipch
set RF=%RF% /RF:*.aps
set RF=%RF% /RF:*.ncb
set RF=%RF% /RF:*.opensdf
set RF=%RF% /RF:*.sdf
set RF=%RF% /RF:*.cachefile

rem Visual Studio profiler
set RF=%RF% /RF:*.psess
set RF=%RF% /RF:*.vsp
set RF=%RF% /RF:*.vspx

rem Guidance Automation Toolkit
set RF=%RF% /RF:*.gpState

rem ReSharper is a .NET coding add-in
set RD=%RD% /RD:_ReSharper*
set RF=%RF% /RF:*.ReSharper

rem TeamCity is a build add-in
set RF=%RF% /RF:_TeamCity*

rem DotCover is a Code Coverage Tool
set RF=%RF% /RF:*.dotCover

rem NCrunch
set RF=%RF% /RF:*.ncrunch*
set RF=%RF% /RF:.*crunch*.local.xml

rem Installshield output folder
set RD=%RD% /RD:Express

rem DocProject is a documentation generator add-in
rem set RD=%RD% /RD:DocProject/buildhelp
rem set RF=%RF% /RF:DocProject/Help/*.HxT
rem set RF=%RF% /RF:DocProject/Help/*.HxC
rem set RF=%RF% /RF:DocProject/Help/*.hhc
rem set RF=%RF% /RF:DocProject/Help/*.hhk
rem set RF=%RF% /RF:DocProject/Help/*.hhp
rem set RF=%RF% /RF:DocProject/Help/Html2
rem set RF=%RF% /RF:DocProject/Help/html

rem Click-Once directory
set RD=%RD% /RD:publish

rem Publish Web Output
set RF=%RF% /RF:*.Publish.xml
set RF=%RF% /RF:*.pubxml

rem NuGet Packages Directory
rem TODO: If you have NuGet Package Restore enabled, uncomment the next line
rem packages

rem Windows Azure Build Output
set RF=%RF% /RF:csx
set RF=%RF% /RF:*.build.csdef

rem Windows Store app package directory
set RD=%RD% /RD:AppPackages

rem Others
set RD=%RD% /RD:sql
set RF=%RF% /RF:*.Cache
set RD=%RD% /RD:ClientBin
set RF=%RF% /RF:StyleCop.*
set RF=%RF% /RF:~$*
set RF=%RF% /RF:*~
set RF=%RF% /RF:*.dbmdl
set RF=%RF% /RF:*.Publish.xml
set RF=%RF% /RF:*.pfx
set RF=%RF% /RF:*.publishsettings

rem RIA/Silverlight projects
set RD=%RD% /RD:Generated_Code

rem Backup & report files from converting an old project file to a newer
rem Visual Studio version. Backup files are not needed, because we have git ;-)
set RD=%RD% /RD:_UpgradeReport_Files
set RD=%RD% /RD:Backup*
set RF=%RF% /RF:UpgradeLog*.XML
set RF=%RF% /RF:UpgradeLog*.htm

rem SQL Server files
rem set RF=%RF% /RF:App_Data/*.mdf
rem set RF=%RF% /RF:App_Data/*.ldf

rem Windows image file caches
set RF=%RF% /RF:Thumbs.db
set RF=%RF% /RF:ehthumbs.db

rem Folder config file
set RF=%RF% /RF:Desktop.ini

rem Recycle Bin used on file shares
set RD=%RD% /RD:$RECYCLE.BIN

rem Mac crap
set RF=%RF% /RF:.DS_Store

cleanproject.exe %RF% %RD% %*
goto EXIT

rem ============
rem Help Command Display
rem ============
:HELP
echo
echo Invokes the Clean Project with a configuration based on GitHub
echo gitignore file for Visual Studio projects.  This includes temporary files,
echo build results, and files generated by popular Visual Studio add-ons.
echo.
echo Invoke-CleanProject [arguments]
echo.
echo    arguments   The arguments to be passed on to cleanproject
echo.

rem ============
rem Exit
rem ============
:EXIT
